name: anigen
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - numpy=1.19.2
  - pip:
    - huggingface-hub==0.10.1
    - diffusers>=0.11
    - transformers>=4.3.1
    - torch==2.1.0
    - torch-fidelity==0.3.0
    - accelerate>=0.11
    - flask==3.0.0
